<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE termlist [
<!ELEMENT termlist (term)*>
<!ELEMENT term (name, parts, translation, language, instance*)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT parts (#PCDATA)>
<!ELEMENT translation (#PCDATA)>
<!ELEMENT language (#PCDATA)>
<!ELEMENT instance (part)+>
<!ELEMENT part EMPTY>
<!ATTLIST termlist

  xmlns:xlink     CDATA           #FIXED "http://www.w3.org/1999/xlink">
<!ATTLIST term
  id              ID              #IMPLIED>
<!ATTLIST instance
  xlink:type      (simple)        #FIXED "simple"
  xlink:href      CDATA           #REQUIRED
  id              ID              #IMPLIED
  creator         CDATA           #IMPLIED
  date            CDATA           #IMPLIED
  status          CDATA           #IMPLIED>
<!ATTLIST part
  word            CDATA           #REQUIRED
  number          CDATA           #REQUIRED
  lemma           CDATA           #IMPLIED>
]>
<termlist xmlns:xlink="http://www.w3.org/1999/xlink">
  <term xml:id="X101ef4a2888">
    <name>du/namis</name>
    <parts>1</parts>
    <translation>power</translation>
    <language>el</language>
    <comment/>
    <instance creator="mjs" date="Tue Feb 08 14:09:47 EST 2005"
      xlink:href="088.xml#id.000303" xml:id="X101f36091f6">
      <part lemma="du/namis" number="1" word="duna/mews"/>
    </instance>
    <instance creator="mjs" date="Tue Feb 08 14:14:52 EST 2005"
      xlink:href="088.xml#id.000304" xml:id="X101f3653a1a">
      <part lemma="du/namis" number="1" word="du/namin"/>
    </instance>
    <instance creator="mjs" date="Fri Feb 11 17:01:52 EST 2005"
      xlink:href="088.xml#id.000334" xml:id="X102037131db">
      <part lemma="du/namis" number="1" word="duna/mei"/>
    </instance>
    <instance creator="mjs" date="Tue Jun 21 15:17:48 CEST 2005"
      xlink:href="088.xml#id.000127" xml:id="X1049f0c1ccb">
      <part lemma="du/namis" number="1" word="duna/mei"/>
    </instance>
    <instance creator="mjs" date="Tue Jun 21 15:18:51 CEST 2005"
      xlink:href="088.xml#id.000128" xml:id="X1049f0d13d0">
      <part lemma="du/namis" number="1" word="duna/mei"/>
    </instance>
    <instance creator="mjs" date="Tue Jun 21 15:19:26 CEST 2005"
      xlink:href="088.xml#id.000129" xml:id="X1049f0d9dfa">
      <part lemma="du/namis" number="1" word="duna/mei"/>
    </instance>
    <instance creator="mjs" date="Tue Jun 21 15:19:39 CEST 2005"
      xlink:href="088.xml#id.000129" xml:id="X1049f0dce05">
      <part lemma="du/namis" number="1" word="duna/mews"/>
    </instance>
    <instance creator="mjs" date="Tue Jun 21 15:20:38 CEST 2005"
      xlink:href="088.xml#id.000130" xml:id="X1049f0eb6e5">
      <part lemma="du/namis" number="1" word="duna/mews"/>
    </instance>
    <instance creator="mjs" date="Fri Feb 11 22:04:43 EST 2005"
      xlink:href="088.xml#id.000322" xml:id="X10204867871">
      <part lemma="du/namis" number="1" word="du/namin"/>
    </instance>
    <instance creator="mjs" date="Fri Feb 11 22:05:02 EST 2005"
      xlink:href="088.xml#id.000297" xml:id="X1020486c09b">
      <part lemma="du/namis" number="1" word="duna/mewn"/>
    </instance>
    <instance creator="mjs" date="Fri Feb 11 22:05:16 EST 2005"
      xlink:href="088.xml#id.000298" xml:id="X1020486f5f5">
      <part lemma="du/namis" number="1" word="duna/meis"/>
    </instance>
    <instance creator="mjs" date="Fri Feb 11 22:05:33 EST 2005"
      xlink:href="088.xml#id.000305" xml:id="X102048738fe">
      <part lemma="du/namis" number="1" word="du/namis"/>
    </instance>
    <instance creator="mjs" date="Fri Feb 11 22:05:45 EST 2005"
      xlink:href="088.xml#id.000309" xml:id="X10204876a3a">
      <part lemma="du/namis" number="1" word="du/namis"/>
    </instance>
    <instance creator="mjs" date="Fri Feb 11 22:05:59 EST 2005"
      xlink:href="088.xml#id.000334" xml:id="X1020487a1b0">
      <part lemma="du/namis" number="1" word="duna/mewn"/>
    </instance>
    <instance creator="mjs" date="Fri Feb 11 22:18:33 EST 2005"
      xlink:href="088.xml#id.000318" xml:id="X10204931fed">
      <part lemma="du/namis" number="1" word="du/namis"/>
    </instance>
    <instance creator="mjs" date="Fri Feb 11 22:23:26 EST 2005"
      xlink:href="088.xml#id.000318" xml:id="X102049797cf">
      <part lemma="du/namis" number="1" word="duna/mewn"/>
    </instance>
    <instance creator="mjs" date="Tue Jun 21 15:18:28 CEST 2005"
      xlink:href="088.xml#id.000128" xml:id="X1049f0cbba0">
      <part lemma="du/namis" number="1" word="duna/mewn"/>
    </instance>
    <instance creator="mjs" date="Tue Jun 21 15:19:04 CEST 2005"
      xlink:href="088.xml#id.000128" xml:id="X1049f0d45ca">
      <part lemma="du/namis" number="1" word="du/namin"/>
    </instance>
    <instance creator="mjs" date="Tue Jul 05 11:27:17 CEST 2005"
      xlink:href="088.xml#id.000332" xml:id="X104e6521ca7">
      <part lemma="du/namis" number="1" word="du/namin"/>
    </instance>
  </term>
  <term xml:id="X101ef4cd933">
    <name>sxh=ma</name>
    <parts>1</parts>
    <translation>form</translation>
    <language>el</language>
    <comment/>
    <instance creator="mjs" date="Mon Feb 07 19:09:54 EST 2005"
      xlink:href="088.xml#id.000297" xml:id="X101ef4cfa8c">
      <part lemma="sxh=ma" number="1" word="sxh/mata"/>
    </instance>
    <instance creator="mjs" date="Mon Feb 07 19:21:36 EST 2005"
      xlink:href="088.xml#id.000298" xml:id="X101ef57aff6">
      <part lemma="sxh=ma" number="1" word="sxh/masin"/>
    </instance>
    <instance creator="mjs" date="Fri Apr 21 11:05:25 EDT 2006"
      xlink:href="088.xml#id.000014" xml:id="X10abcfbe485">
      <part lemma="" number="1" word="sxh=ma"/>
    </instance>
    <instance creator="mjs" date="Fri Apr 21 11:05:25 EDT 2006"
      xlink:href="088.xml#id.000027" xml:id="X10abcfbe49c">
      <part lemma="" number="1" word="sxh/mati"/>
    </instance>
    <instance creator="mjs" date="Fri Apr 21 11:05:25 EDT 2006"
      xlink:href="088.xml#id.000030" xml:id="X10abcfbe4b0">
      <part lemma="" number="1" word="sxh/matos"/>
    </instance>
    <instance creator="mjs" date="Fri Apr 21 11:05:25 EDT 2006"
      xlink:href="088.xml#id.000030" xml:id="X10abcfbe4c2">
      <part lemma="" number="2" word="sxh/matos"/>
    </instance>
    <instance creator="mjs" date="Fri Apr 21 11:05:25 EDT 2006"
      xlink:href="088.xml#id.000288" xml:id="X10abcfbe4d4">
      <part lemma="" number="1" word="sxh/mata"/>
    </instance>
  </term>
  <term xml:id="X101ef4d22f1">
    <name>xrei/a</name>
    <parts>1</parts>
    <translation>use</translation>
    <language>el</language>
    <comment/>
    <instance creator="mjs" date="Mon Feb 07 19:10:06 EST 2005"
      xlink:href="088.xml#id.000297" xml:id="X101ef4d2905">
      <part lemma="xrei/a" number="1" word="xrei/as"/>
    </instance>
    <instance creator="mjs" date="Tue Feb 08 14:07:42 EST 2005"
      xlink:href="088.xml#id.000302" xml:id="X101f35eaa7a">
      <part lemma="xrei/a" number="1" word="xrei/a"/>
    </instance>
    <instance creator="mjs" date="Fri Feb 11 13:07:14 EST 2005"
      xlink:href="088.xml#id.000321" xml:id="X102029a62f9">
      <part lemma="xrei/a" number="1" word="xrei/ais"/>
    </instance>
    <instance creator="mjs" date="Fri Feb 11 22:18:43 EST 2005"
      xlink:href="088.xml#id.000318" xml:id="X1020493475c">
      <part lemma="xrei/a" number="1" word="xrei/as"/>
    </instance>
  </term>
  <term xml:id="X101ef4d6e9a">
    <name>o)/noma</name>
    <parts>1</parts>
    <translation>name</translation>
    <language>el</language>
    <comment/>
    <instance creator="mjs" date="Mon Feb 07 19:10:26 EST 2005"
      xlink:href="088.xml#id.000297" xml:id="X101ef4d78be">
      <part lemma="o)/noma" number="1" word="o)no/mata"/>
    </instance>
    <instance creator="mjs" date="Mon Feb 07 22:15:19 EST 2005"
      xlink:href="088.xml#id.000299" xml:id="X101eff6b9c4">
      <part lemma="o)/noma" number="1" word="o)no/mata"/>
    </instance>
  </term>
  <term xml:id="X101ef4e5ab2">
    <name>quw~ap_1</name>
    <parts>1</parts>
    <translation>force</translation>
    <language>ar</language>
    <comment/>
    <instance creator="mjs" date="Mon Feb 07 19:11:27 EST 2005"
      xlink:href="098.xml#id.52.0.02.01" xml:id="X101ef4e64b0">
      <part lemma="qWy" number="1" word="AlqwY"/>
    </instance>
    <instance creator="mjs" date="Mon Feb 07 19:15:29 EST 2005"
      xlink:href="096.xml#A18-2|01|01" xml:id="X101ef52160b">
      <part lemma="qWy" number="1" word="Aal-quwY"/>
    </instance>
    <instance creator="mjs" date="Mon Feb 07 19:17:24 EST 2005"
      xlink:href="096.xml#A18-2|01|01" xml:id="X101ef53d905">
      <part lemma="qWy" number="2" word="Aal-quwY"/>
    </instance>
    <instance creator="mjs" date="Mon Feb 07 19:20:18 EST 2005"
      xlink:href="098.xml#id.52.0.02.02" xml:id="X101ef56801c">
      <part lemma="qWy" number="1" word="AlqwY"/>
    </instance>
    <instance creator="mjs" date="Tue Feb 08 17:05:18 EST 2005"
      xlink:href="098.xml#id.55.0.01.01" xml:id="X101f40142b1">
      <part lemma="Alqw~p" number="1" word="Alqw~p"/>
    </instance>
    <instance creator="mjs" date="Tue Feb 08 17:05:25 EST 2005"
      xlink:href="096.xml#A18-2|03|01" xml:id="X101f4015d92">
      <part lemma="Aal-quw~ap" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Tue Feb 08 17:05:29 EST 2005"
      xlink:href="096.xml#A18-2|03|02" xml:id="X101f4016eb1">
      <part lemma="Aal-quw~ap" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 09 17:20:56 EST 2005"
      xlink:href="098.xml#id.54.0.01.01" xml:id="X101f935edea">
      <part lemma="Alqw~p" number="1" word="Alqw~p"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 09 18:58:18 EST 2005"
      xlink:href="098.xml#id.53.0.02.09" xml:id="X101f98f130d">
      <part lemma="bqw~p" number="1" word="bqw~p"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 09 19:13:45 EST 2005"
      xlink:href="098.xml#id.53.0.02.11" xml:id="X101f99d39d8">
      <part lemma="bqw~p" number="1" word="bqw~p"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 09 19:22:40 EST 2005"
      xlink:href="098.xml#id.53.0.02.13" xml:id="X101f9a563a2">
      <part lemma="Alqw~p" number="1" word="Alqw~p"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 09 19:31:48 EST 2005"
      xlink:href="096.xml#A18-2|01|14" xml:id="X101f9adbd8d">
      <part lemma="Aal-quw~ap" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Mon Feb 14 18:14:59 EST 2005"
      xlink:href="096.xml#A18-2|01|11" xml:id="X10213273543">
      <part lemma="bi-quw~ap" number="1" word="bi-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Mon Feb 14 18:26:37 EST 2005"
      xlink:href="096.xml#A18-2|01|12" xml:id="X1021331dde2">
      <part lemma="bi-quw~ap" number="1" word="bi-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Mon Feb 14 18:52:32 EST 2005"
      xlink:href="096.xml#A18-2|02|02" xml:id="X102134997ca">
      <part lemma="Aal-quw~ap" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Mon Feb 14 18:54:01 EST 2005"
      xlink:href="096.xml#A18-2|02|02" xml:id="X102134af380">
      <part lemma="Aal-quw~ap" number="2" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Tue Feb 15 20:14:21 EST 2005"
      xlink:href="096.xml#A18-2|02|05" xml:id="X10218badc10">
      <part lemma="Aal-quw~ap" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 17:08:52 EST 2005"
      xlink:href="096.xml#A18-2|04|01" xml:id="X1021d376581">
      <part lemma="Aal-quw~ap" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 17:08:57 EST 2005"
      xlink:href="096.xml#A18-2|04|02" xml:id="X1021d3778b1">
      <part lemma="Aal-quw~ap" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 17:09:15 EST 2005"
      xlink:href="096.xml#A18-2|04|02" xml:id="X1021d37c209">
      <part lemma="Aal-quw~ap" number="2" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 17:57:00 EST 2005"
      xlink:href="096.xml#A18-2|04|05" xml:id="X1021d637779">
      <part lemma="qWy" number="1" word="Aal-quwY"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 17:57:19 EST 2005"
      xlink:href="096.xml#A18-1|29|01" xml:id="X1021d63c0d3">
      <part lemma="" number="1" word="Aal-quwY"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 17:57:19 EST 2005"
      xlink:href="096.xml#A18-1|29|06" xml:id="X1021d63c0d8">
      <part lemma="" number="1" word="Aal-quwY"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 17:57:19 EST 2005"
      xlink:href="096.xml#A18-1|29|06" xml:id="X1021d63c0de">
      <part lemma="" number="2" word="Aal-quwY"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 17:57:19 EST 2005"
      xlink:href="096.xml#A18-2|20|01" xml:id="X1021d63c0e4">
      <part lemma="" number="1" word="Aal-quwY"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 17:57:19 EST 2005"
      xlink:href="096.xml#A18-2|20|03" xml:id="X1021d63c0e8">
      <part lemma="" number="1" word="Aal-quwY"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 17:57:19 EST 2005"
      xlink:href="096.xml#A18-2|32|01" xml:id="X1021d63c0ed">
      <part lemma="" number="1" word="Aal-quwY"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 17:57:19 EST 2005"
      xlink:href="096.xml#A18-2|32|02" xml:id="X1021d63c0f1">
      <part lemma="" number="1" word="Aal-quwY"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 17:57:19 EST 2005"
      xlink:href="096.xml#A18-2|33|01" xml:id="X1021d63c0f6">
      <part lemma="" number="1" word="Aal-quwY"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 17:57:19 EST 2005"
      xlink:href="096.xml#A18-2|33|08" xml:id="X1021d63c0fa">
      <part lemma="" number="1" word="Aal-quwY"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:06:04 EST 2005"
      xlink:href="096.xml#A18-2|04|08" xml:id="X1021d6bc6be">
      <part lemma="bi-quw~atihi" number="1" word="bi-quw~atihi"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-1|01|06" xml:id="X1021d729b46">
      <part lemma="" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-1|01|08" xml:id="X1021d729b4b">
      <part lemma="" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-1|01|09" xml:id="X1021d729b50">
      <part lemma="" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-1|01|09" xml:id="X1021d729b55">
      <part lemma="" number="2" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-1|01|10" xml:id="X1021d729b5a">
      <part lemma="" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-1|01|10" xml:id="X1021d729b5f">
      <part lemma="" number="2" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-1|20|02" xml:id="X1021d729b64">
      <part lemma="" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-1|20|07" xml:id="X1021d729b69">
      <part lemma="" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-1|22|02" xml:id="X1021d729b6e">
      <part lemma="" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-1|23|03" xml:id="X1021d729b73">
      <part lemma="" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-1|23|08" xml:id="X1021d729b78">
      <part lemma="" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-1|29|06" xml:id="X1021d729b7d">
      <part lemma="" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-1|29|07" xml:id="X1021d729b82">
      <part lemma="" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-1|29|07" xml:id="X1021d729b87">
      <part lemma="" number="2" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|05|01" xml:id="X1021d729b8c">
      <part lemma="" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|07|10" xml:id="X1021d729b91">
      <part lemma="" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|07|10" xml:id="X1021d729b96">
      <part lemma="" number="2" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|08|10" xml:id="X1021d729b9b">
      <part lemma="" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|08|11" xml:id="X1021d729b9f">
      <part lemma="" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|08|11" xml:id="X1021d729ba4">
      <part lemma="" number="2" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|09|10" xml:id="X1021d729ba9">
      <part lemma="" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|09|14" xml:id="X1021d729bae">
      <part lemma="" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|09|15" xml:id="X1021d729bb2">
      <part lemma="" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|10|02" xml:id="X1021d729bb7">
      <part lemma="" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|10|02" xml:id="X1021d729bbc">
      <part lemma="" number="2" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|12|08" xml:id="X1021d729bc1">
      <part lemma="" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|12|08" xml:id="X1021d729bc6">
      <part lemma="" number="2" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|12|08" xml:id="X1021d729bcb">
      <part lemma="" number="3" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|12|09" xml:id="X1021d729bd1">
      <part lemma="" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|12|09" xml:id="X1021d729bd6">
      <part lemma="" number="2" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|12|10" xml:id="X1021d729bdb">
      <part lemma="" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|12|11" xml:id="X1021d729be0">
      <part lemma="" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|12|12" xml:id="X1021d729be5">
      <part lemma="" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|12|12" xml:id="X1021d729bea">
      <part lemma="" number="2" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|13|01" xml:id="X1021d729bef">
      <part lemma="" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|13|03" xml:id="X1021d729bf3">
      <part lemma="" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|13|05" xml:id="X1021d729bf8">
      <part lemma="" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|13|09" xml:id="X1021d729bfd">
      <part lemma="" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|13|10" xml:id="X1021d729c02">
      <part lemma="" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|13|10" xml:id="X1021d729c07">
      <part lemma="" number="2" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|15|18" xml:id="X1021d729c0c">
      <part lemma="" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|17|02" xml:id="X1021d729c11">
      <part lemma="" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|20|06" xml:id="X1021d729c16">
      <part lemma="" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|21|05" xml:id="X1021d729c1b">
      <part lemma="" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|21|05" xml:id="X1021d729c21">
      <part lemma="" number="2" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|21|09" xml:id="X1021d729c26">
      <part lemma="" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|21|10" xml:id="X1021d729c2b">
      <part lemma="" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|21|14" xml:id="X1021d729c30">
      <part lemma="" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|21|15" xml:id="X1021d729c35">
      <part lemma="" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|21|16" xml:id="X1021d729c3a">
      <part lemma="" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|21|18" xml:id="X1021d729c3f">
      <part lemma="" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|21|19" xml:id="X1021d729c44">
      <part lemma="" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|21|20" xml:id="X1021d729c49">
      <part lemma="" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|22|01" xml:id="X1021d729c4e">
      <part lemma="" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|22|01" xml:id="X1021d729c53">
      <part lemma="" number="2" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|22|01" xml:id="X1021d729c58">
      <part lemma="" number="3" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|22|01" xml:id="X1021d729c5d">
      <part lemma="" number="4" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|22|07" xml:id="X1021d729c62">
      <part lemma="" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|22|07" xml:id="X1021d729c67">
      <part lemma="" number="2" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|23|01" xml:id="X1021d729c6b">
      <part lemma="" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|23|03" xml:id="X1021d729c70">
      <part lemma="" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|23|04" xml:id="X1021d729c75">
      <part lemma="" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|23|05" xml:id="X1021d729c7a">
      <part lemma="" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|23|06" xml:id="X1021d729c7f">
      <part lemma="" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|23|07" xml:id="X1021d729c84">
      <part lemma="" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|24|02" xml:id="X1021d729c89">
      <part lemma="" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|24|03" xml:id="X1021d729c8e">
      <part lemma="" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|24|03" xml:id="X1021d729c93">
      <part lemma="" number="2" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|25|01" xml:id="X1021d729c98">
      <part lemma="" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|25|04" xml:id="X1021d729c9e">
      <part lemma="" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|25|05" xml:id="X1021d729ca3">
      <part lemma="" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|25|06" xml:id="X1021d729ca8">
      <part lemma="" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|25|07" xml:id="X1021d729cad">
      <part lemma="" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|25|08" xml:id="X1021d729cb2">
      <part lemma="" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|26|04" xml:id="X1021d729cb7">
      <part lemma="" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|26|04" xml:id="X1021d729cbc">
      <part lemma="" number="2" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|27|01" xml:id="X1021d729cc1">
      <part lemma="" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|28|03" xml:id="X1021d729cc5">
      <part lemma="" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|29|06" xml:id="X1021d729cca">
      <part lemma="" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|29|11" xml:id="X1021d729ccf">
      <part lemma="" number="1" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"
      xlink:href="096.xml#A18-2|29|11" xml:id="X1021d729cd4">
      <part lemma="" number="2" word="Aal-quw~ap"/>
    </instance>
    <instance creator="mjs" date="Wed Feb 16 18:13:32 EST 2005"