=== SeanyWang/despecs/texts/archimedesOldCVSRepository/archimedes/dtd/archimedes.dtd
<!-- footnotes and margnotes get yanked out of their <p>s, repl. by <arrow>, -->
<!-- and moved to own p.  -->

<!ELEMENT foot.target 
	(#PCDATA)  >
<!-- e.g. number in front of a footnote -->

<!ATTLIST foot.target
    	id ID #REQUIRED
	n CDATA #IMPLIED >


<!ELEMENT margin.target 
	(#PCDATA)  >

<!ATTLIST margin.target
    	id ID #REQUIRED
	n CDATA #IMPLIED >

<!ELEMENT table.target 
	(#PCDATA)  >

<!ATTLIST table.target
    	id ID #REQUIRED
	n CDATA #IMPLIED >

<!ELEMENT arrow.to.target 
	(#PCDATA)*  >

<!ATTLIST arrow.to.target
        symbol 		CDATA #IMPLIED
    	id 		ID #IMPLIED
	n 		CDATA #IMPLIED
  	xlink:type      (simple)        #FIXED "simple"
  	xlink:href      CDATA           #IMPLIED>

<!-- reference to removed figure/note. contains mark in text. -->
<!-- n attribute contains id of referent target -->
<!-- Can marginalia ever have referring marks in text? -->


<!ELEMENT archimedes 
	(info, text) >


<!ATTLIST archimedes 
	id ID #IMPLIED
        xmlns:xml       CDATA           #FIXED "http://www.w3.org/XML/1998/namespace"
	xmlns:xlink     CDATA           #FIXED "http://www.w3.org/1999/xlink"
	n CDATA #IMPLIED >


<!ELEMENT author 
	(#PCDATA) >


<!ATTLIST author
	id ID #IMPLIED
	n CDATA #IMPLIED >


<!ELEMENT back
        ( section | pb?)+ >

<!ATTLIST back
        id ID #IMPLIED
        n CDATA #IMPLIED 
        type CDATA #IMPLIED>


<!ELEMENT body
       (chap |  pb?)+ >

<!ATTLIST body
        id ID #IMPLIED
        n CDATA #IMPLIED >

<!ELEMENT comments       (#PCDATA)   >

<!ATTLIST comments
        id ID #IMPLIED
        n CDATA #IMPLIED >


<!ELEMENT cvs_file
        (#PCDATA) >


<!ATTLIST cvs_file
        id ID #IMPLIED
        n CDATA #IMPLIED >


<!ELEMENT cvs_version
        (#PCDATA) >


<!ATTLIST cvs_version
        id ID #IMPLIED
        n CDATA #IMPLIED >


<!ELEMENT chap 
	(  p | pb | figure | table | subchap1)+ >


<!ATTLIST chap
	id ID #IMPLIED
	n CDATA #IMPLIED
	type CDATA #IMPLIED>

<!ELEMENT subchap1 
	(  p | pb | figure | table | subchap2)+ >


<!ATTLIST subchap1
	id ID #IMPLIED
	n CDATA #IMPLIED
	type CDATA #IMPLIED>

<!ELEMENT subchap2 
	(  p | pb | figure | table )+ >


<!ATTLIST subchap2
	id ID #IMPLIED
	n CDATA #IMPLIED
	type CDATA #IMPLIED>

<!ELEMENT date
        (#PCDATA) >


<!ATTLIST date
        id ID #IMPLIED
        n CDATA #IMPLIED >

<!--  -->
<!ELEMENT emph 
         EMPTY>


<!ATTLIST emph
        type (at|et|italics|bold|sup|sub|over|smallcaps|center|roman|ul|quote|strike|other) "italics" 
	id ID #IMPLIED
	n CDATA #IMPLIED>

<!-- et = erased text
	at = added text
-->

<!ELEMENT emph.end 
         EMPTY>

<!-- the type attrib. here shld be entitized -->
<!ATTLIST emph.end
        type (at|et|italics|bold|sup|sub|over|smallcaps|center|roman|ul|quote|strike|other) "italics" 
	id ID #IMPLIED
	n CDATA #IMPLIED>


<!ELEMENT expan 
	(#PCDATA | foot.target|margin.target|arrow.to.target|pb|lb|emph|emph.end|gap)* >


<!ATTLIST expan 
	id ID #IMPLIED
	n CDATA #IMPLIED
	abbr CDATA #IMPLIED
	type CDATA #IMPLIED >
<!-- expand tags must be placed around the whole word in which abbreviations occur -->

<!ELEMENT figure 
	(#PCDATA) >

<!ATTLIST figure 
	id ID #IMPLIED
	place (margin|text) "text"
  	xlink:type      (simple)        #FIXED "simple"
  	xlink:href      CDATA           #IMPLIED>


<!ELEMENT foreign
       (#PCDATA | expan | figure | var | foot.target|margin.target|arrow.to.target|pb|lb|emph|emph.end|gap)* > 


<!ATTLIST foreign
        id ID #IMPLIED
        n CDATA #IMPLIED
        lang CDATA #IMPLIED>

<!-- <foreign> for text within sentences not in the main lang of the text -->
<!--    or for text within non-default-lang higher elements  -->
<!ELEMENT front
        ( section | pb?)+ >

<!ATTLIST front
        id ID #IMPLIED
        n CDATA #IMPLIED 
        type CDATA #IMPLIED>

<!ELEMENT gap
        EMPTY >

<!ATTLIST gap
        id ID #IMPLIED
        n CDATA #IMPLIED
        desc CDATA #IMPLIED>

<!-- gap is a catch-all tag employed at Perseus and in the TEI to isolate -->
<!-- uncertain DE markup. It appears here for continuity's sake. -->


<!ELEMENT info 
	(author, title, date, place, translator, lang, cvs_file?,cvs_version?,comments?,locator) >
<!-- how many of these should be required? -->
<!-- what about bringing in line with dublin core? -->

<!ATTLIST info 
	id ID #IMPLIED
	n CDATA #IMPLIED >



<!ELEMENT lang
        (#PCDATA) >


<!ATTLIST lang
        id ID #IMPLIED
        n CDATA #IMPLIED >

<!ELEMENT lb         EMPTY                              >

<!ATTLIST lb
          ed                 CDATA               #IMPLIED
          id                 ID                  #IMPLIED
           n                  CDATA               #IMPLIED>
          
<!-- <lb> occurs at <s> level and at <p> level  -->
<!-- <lb> at end of <s> must be placed after </s> -->
<!-- <lb> at beginning of <s> must be placed before <s> -->

<!-- unrecognized symbols will appear inline acc. to special conventions.  -->
<!--   (as in DE specs) -->

<!-- emph and and emph.end are elements that are quer to the xml structure -->

<!ELEMENT locator       (#PCDATA)   >

<!ATTLIST locator
        id ID #IMPLIED
        n CDATA #IMPLIED >

<!ELEMENT p

       (s | figure | pb | lb | emph | emph.end | gap )+ > 


<!ATTLIST p 
	id ID #IMPLIED
	n CDATA #IMPLIED 
        type (main|table|marked|foot|margin|list|head|caption) "main" >
<!-- captions go in paragr's immediately after figure, with arrow.to.target -->
<!-- table is allowed as val for type attr for backward compatibility -->
<!-- pb can occur within p but NOT at the start or end -->


<!ELEMENT pb 
	EMPTY >


<!ATTLIST pb
        ed CDATA #IMPLIED
        id ID #IMPLIED
        n CDATA #IMPLIED 
  	xlink:type      (simple)        #FIXED "simple"
  	xlink:href      CDATA           #IMPLIED
        pagenum CDATA #IMPLIED>

<!-- the "ed"  attribute gives the edition in which the page break occurs. If no -->
<!-- edition is given, it is assumed to be that given in info -->
<!-- pagenum gives the page number actually printed on the page.  -->
<!-- n gives the page number numbered consecutively from page 1 of text. -->
<!-- pb can occur inside <s> etc. and inside <p> and inside <chap> -->
<!-- <pb> at end of <p> must be placed after </p> -->


<!ELEMENT place
        (#PCDATA) >


<!ATTLIST place
        id ID #IMPLIED
        n CDATA #IMPLIED >



<!ELEMENT publisher 
	(#PCDATA)* >


<!ATTLIST publisher
	id ID #IMPLIED
	n CDATA #IMPLIED >


<!ELEMENT s 

(#PCDATA| foreign | figure | expan | var | foot.target|margin.target|arrow.to.target|pb|lb|emph|emph.end|gap)* >

<!-- mdh 2003-07-23

  I've given <s> the special attribute xml:space="preserve", so that
  XML processors will respect whitespace within <s> and its descendants.
  See: "Extensible Markup Language (XML) 1.0", http://www.w3.org/TR/REC-xml,
  sec. 2.10 "White Space Handling".
-->

<!ATTLIST s
        id        ID                 #IMPLIED
        n         CDATA              #IMPLIED
        xml:space (default|preserve) #FIXED "preserve" >

<!ELEMENT section 
	( p | pb | figure | table )+ >


<!ATTLIST section
	id ID #IMPLIED
	n CDATA #IMPLIED
	type CDATA #IMPLIED>

<!ELEMENT table
	( table.target?,  (row, pb?)+ ) >

<!-- order is now:
<table><table.target/><row>...</row><pb>
i.e. <table> is equiv. to <p type=margin>
 -->
<!ATTLIST table
	id ID #IMPLIED 
	n CDATA #IMPLIED >

<!ELEMENT row
	( cell+ ) >

<!ATTLIST row
	id ID #IMPLIED 
	n CDATA #IMPLIED >

<!ELEMENT cell
	(#PCDATA| foreign | expan | var | foot.target|margin.target|arrow.to.target|pb|lb|emph|emph.end|gap)* >

<!ATTLIST cell
	id ID #IMPLIED 
	n CDATA #IMPLIED >

<!-- 2003-12-18 (mdh)

     <var> tag can be used to tag variable names
     Mixed-alphabet variables should be tagged as e.g. <var>DG&Sigma;</var>
-->
<!ELEMENT var 
	(#PCDATA | lb)* >

<!ATTLIST var
	id ID #IMPLIED 
	n CDATA #IMPLIED >

<!ELEMENT text
        (pb?, front, pb?, body, pb?, back?) >

<!-- if front and back are going to be optional, then pb can be allowed to -->
<!-- occur only within front body back.  -->


<!ATTLIST text 
        type CDATA #IMPLIED
	id ID #IMPLIED
	n CDATA #IMPLIED>


<!ELEMENT title 
	(#PCDATA) >

<!ATTLIST title 
	id ID #IMPLIED
	n CDATA #IMPLIED
	type CDATA #IMPLIED >

<!ELEMENT translator 
	(#PCDATA)* >

<!ATTLIST translator
	id ID #IMPLIED
	n CDATA #IMPLIED >


<!-- entities are included below here (2001-11-14; mdh) -->
<!ENTITY % ISOlat1 PUBLIC "ISO 8879:1986//ENTITIES Added Latin 1//EN//XML"
         "ISOlat1.pen">
%ISOlat1;

<!ENTITY % ISOlat2 PUBLIC "ISO 8879:1986//ENTITIES Added Latin 2//EN//XML"
         "ISOlat2.pen">
%ISOlat2;

<!ENTITY % archimedes SYSTEM "archimedes.pen">
%archimedes;

=== SeanyWang/despecs/texts/archimedesOldCVSRepository/archimedes/xml/arist_mecha_102_en_2003.xml
<?xml version="1.0"?>
<!DOCTYPE archimedes SYSTEM "../dtd/archimedes.dtd" >
<archimedes>
<info>
    <author>Pseudo-Aristotle</author>
    <title>Nutaf min al-hiyal (English)</title> 
    <date>2003</date>
    <place>Harvard</place>
    <translator>ek</translator>
    <lang>en</lang>
    <cvs_file></cvs_file>
    <cvs_version></cvs_version>
    <locator>102.xml</locator>
</info>
<text>
<front/>
<body>
<chap>
<p n="1">
<s id="A010010001">Elements/Extracts of Mechanics.  Aristotle said: People marvel either at things which occur in accordance with nature and of which the cause is not known, or at things which are contrary to nature, and are produced by art for the benefit of mankind.  For nature always follows the same direction, whereas the needs of humans  differ widely.</s>
<s id="A010010101">And in every difficult action which happens contrary to nature, mechanical artifices are needed, and for this reason the lesser things overcome the greater things.</s>
<s id="A010010102">The mechanical problems have a share in both the mathematical and the natural sciences, for the &lsquo;how&rsquo; in them belongs to the mathematical sciences, whereas the &lsquo;what&rsquo; belongs to the natural sciences, as in the operation of the lever: when the load is increased, the heavy thing is moved [more] rapidly.</s>
<s id="A010010103">The circle is the cause of all this, and the like.</s>
<s id="A010010104">The most marvelous is that in which contrary things are combined, and in the circle are combined motion and rest. In its circumference sinking and rising exist, and between them the tangent, just as the equal exists between the greater and the smaller, and the straight between the concave and the convex.</s>
<s id="A010010105">And in one and the same movement of the circle, there exists contrariety between forward and backward, upward and downward.</s>
<s id="A010010106">A line draws it by motion on one side and by rest on the other, ending where it started and proceeding to what it has left.</s>
<s id="A010010107">The motions of the points posited on it differ in speed, the one closer to the end at rest being slower.</s>
<s id="A010010108">Therefore, the circle is undeniably the origin and principle of any and every marvel.</s>
<s id="A010010201">The things that occur in the case of the balance occur only because of the circle and are referred to it, whereas those which occur in the case of the lever are referred to the balance.</s>
<s id="A010010202">And since a single circle can move with two different motions, it is possible to produce circles that move with a single motion, from which many motions come about.</s>
<s id="A010010203">This is the origin of many contrary and marvelous motions; only one of them is obvious, but its cause is hidden.</s>
</p>
<p n="2" type="head">
<s id="A010020001">Problem</s>
</p>
<p n="3">
<s id="A010020101">It is also asked why the large balances are more accurate and of more precision than the small balances.</s>
<s id="A010020102">The principle of the answer regarding this cause is to ask why, in the case of a line that departs from the center of a circle and is long, and therefore the distance of its end from the center is a greater distance, the motion of its end is faster when both ends are moved by the same force.</s>
<s id="A010020103">The faster of two mobiles is the one that travels over a greater distance in the same time.</s>
<s id="A010020104">And the farther from the center travels over a greater distance along its circumference, and the nearer a smaller distance.</s>
<s id="A010020105">It is evident from this reasoning that the suspension of the balance is a center, since it is fixed, and because the two sides of the beam, which are on either side of the suspension, stand for the lines departing from the center.</s>
<s id="A010020106">If the beam is longer, the motion of its end, as it is caused by the same weight, will be stronger than the motion it would have if it were shorter.</s>
<s id="A010020107">Hence, when some weights are put on small balances, they do not produce any inclination toward their side, because of their smallness and the shortness of the beam.</s>
<s id="A010020108">But if they are put on a large balance, an evident inclination results, because of the length of the needle and of the beam.</s>
</p>
</chap>
</body>
<back/>
</text>
</archimedes>

=== SeanyWang/despecs/texts/archimedesOldCVSRepository/archimedes/xml/eucli_ponde_059_it_1565.xml
<?xml version="1.0"?>
<!DOCTYPE archimedes SYSTEM "../dtd/archimedes.dtd">
<archimedes xmlns:xlink="http://www.w3.org/1999/xlink">      <info>
        <author>Pseudo Euclid</author>
        <title>de ponderoso et levi</title>
        <date>1565</date>
        <place>Venice</place>
        <translator>Tartaglia</translator>
        <lang>fr</lang>
        <cvs_file>eucli_ponde_059_it_1565.xml</cvs_file>
        <cvs_version/>
        <locator>059.xml</locator>
</info>      <text>
<pb xlink:href="059/01/001.jpg" /><front>

<section><p type="head"><s id="id.000001">PARTICELLA DELLA COSA LEGGIERA,<lb/>ET GRAVE D'EVCLIDE</s></p></section></front><body><chap><p type="main">
<s id="id.000002">1 I CORPI vguali di grandezza &longs;ono quelli, che riempieno i luoghi uguali.</s></p><p>
<s id="id.000003">2 I corpi diuer&longs;i di grandezza &longs;ono quelli, che riempieno i luoghi non uguali.</s></p><p>
<s id="id.000004">3 I corpi maggiori di grandezza &longs;i dicono quei, iquali &longs;ono di luoghi piu amplo.</s></p><p>
<s id="id.000005">4 I corpi uguali di potentia &longs;ono quelli, i moti de iquali &longs;ono uguali, per mezzo e di t<expan abbr="&etilde;">em</expan><lb/>po e d'aria, o d'acqua ugali, &amp; per &longs;patii uguali.</s></p><p>
<s id="id.000006">5 I corpi diuer&longs;i di potentia &longs;ono, i moti d'iquali &longs;ono uguali a diuer&longs;o tempo.</s></p><p>
<s id="id.000007">6 De i corpi diuer&longs;i di potentia, quello &longs;i dice il maggior di potentia, il quale mouendo&longs;i<lb/>con&longs;uma manco tempo. il menor di potentia &egrave; que&longs;to, che con&longs;uma piu tempo.</s></p><p>
<s id="id.000008">7 I corpi della i&longs;te&longs;&longs;a &longs;orte &longs;ono quelli, che e&longs;&longs;endo uguali di grandezza &longs;ono anco di<lb/>potentia.</s></p><p>
<s id="id.000009">8 I corpi di diuer&longs;a &longs;orte &longs;ono quelli, iquali e&longs;&longs;endo di grandezza uguali, non &longs;ono di po<lb/>tentia, benche &longs;i muouano per lo mede&longs;imo mezo.</s></p><p>
<s id="id.000010">9 De i corpi di diuer&longs;a &longs;orte il piu potente &longs;i dice que&longs;to, che &egrave; piu &longs;odo.</s></p><p type="head">
<s id="id.000011"><emph type="italics"/>Theorema primo<emph.end type="italics"/></s></p><p type="main">
<s id="id.000012">De i corpi de diuer&longs;a di potentia quello, che per il maggior &longs;patio &longs;i moue, ha piu pot<expan abbr="&etilde;">en</expan>tia.</s></p><p>
<s id="id.000013">Siano a. e .b. due corpi. </s>
<s id="id.000014">Siano .g.d. &amp; e.f. due &longs;patii .g.<lb/>d. il  maggior, per loqual lo a. &longs;i moue .e.f. il menor, per lo<lb/><figure id="id.059.01.001.1.jpg" xlink:href="059/01/001/1.jpg"/>qual il b. &longs;i moue. </s>
<s id="id.000015">Ri&longs;ecarto dal &longs;patio di .g.d. il &longs;patio di<lb/>g.r. di modo, che &longs;ia al &longs;patio di. e.f. uguale il &longs;patio di .g.<lb/>r. il rimanente &egrave; chiaro da &longs;e.</s></p><p type="head">
<s id="id.000016"><emph type="italics"/>Theorema &longs;econdo<emph.end type="italics"/></s></p><p type="main">
<s id="id.000017">Se i corpi dell'i&longs;te&longs;&longs;a &longs;orte &longs;aranno tra &longs;e moltiplici, &longs;a<lb/>ranno parimente le loro potentie moltiplici.</s></p><p>
<s id="id.000018">Sia il corpo .a.g. doppio al corpo .d. della mede&longs;ima &longs;orte, dico e&longs;&longs;er anco doppio di po<lb/>t<expan abbr="&etilde;">en</expan>tia.</s>
<s id="id.000019">Perci&ograve; del corpo .a.g. &longs;ia la potentia .e.h. </s>
<s id="id.000020">Del d. poi il c. &amp; a.g. &longs;econdo l'ecce&longs;&longs;o del <lb/>moltiplice &longs;i parta in a,b. &amp; b,g. di maniera che la pot<expan abbr="&etilde;">en</expan>tia<lb/><figure id="id.059.01.001.2.jpg" xlink:href="059/01/001/2.jpg"/>dell'uno e del'altro &longs;i &longs;ia uguale alla potentia del copo di<lb/>e&longs;&longs;o d, laqual era c.</s>
<s id="id.000021">Dapoi partimmo il corpo a,g, nelle par<lb/>ti, a,b. b,g, pari al corpo d. co&longs;i partiamo la potentia .e,h.<lb/>nelle parti ,e,r, &amp; ,r,h, pari alla potentia del .c. egli &egrave; mani<lb/>fe&longs;to, che la potentia .e.h. riu&longs;ci&longs;ca doppia potentia.</s></p><p type="head">
<s id="id.000022"><emph type="italics"/>Theorema terzo<emph.end type="italics"/></s></p><p type="main">
<s id="id.000023">De i corpi dell'i&longs;te&longs;&longs;a &longs;orte &egrave; una  medi&longs;ima proportione<lb/>&amp; di grandezza e di potentia.</s></p><p>
<s id="id.000024">Sia il corpo .a. doppio del corpo .b. della mede&longs;ima &longs;orte.<lb/><figure id="id.059.01.001.3.jpg" xlink:href="059/01/001/3.jpg"/>dico come il corpo .a. e al corpo .b. co&longs;i il g. potentia del cor<lb/>po .a. &longs;ia chiaro e&longs;&longs;er al .d. potentia del corpo .b. &longs;e al modo,<lb/>che partiamo i corpi, co&longs;i partiamo parimente le potentie<lb/>molticheuolmente dall'una e dall'altra parte.</s></p><p type="head">
<s id="id.000025"><emph type="italics"/>Theorema quarto<emph.end type="italics"/></s></p><p type="main">
<s id="id.000026">I corpi &longs;ono dell'i&longs;te&longs;&longs;a &longs;orte tra di &longs;e, iquali &longs;ono di par <lb/>pot<expan abbr="&etilde;">en</expan>tia el corpo della mede&longs;ima &longs;orte, perche tolte le ugua<lb/>lit&agrave; a quel terzo &longs;aranno le virt&ugrave; loro pari percioche &longs;ono <lb/>uguali le potentie del terzo.</s></p><p>
<s id="id.000027">Saranno i corpi della &longs;orte mede&longs;ima, de iquali e una proportione &amp; grandezza, &amp; <lb/>di potentia, </s>
<s id="id.000028">Se come  il corpo .a. al corpo .b. co&longs;i la potentia del corpo ,a, al d, potentia del <lb/>corpo ,b, dico i corpi .a. b. e&longs;&longs;ere dell'i&longs;te&longs;&longs;a &longs;orte, percioche poniamo il corpo ,a, ugual al <lb/>corpo, la potentia del qual &longs;ia lo .r. </s>
<s id="id.000029">Saranno adonque come il b. allo .a. co&longs;i lo .r. alla poten<lb/>tia di e&longs;&longs;o .a. laquale e il g. </s>
<s id="id.000030">Il re&longs;to e manife&longs;to.</s></p><p type="head">
<s id="id.000031">IL FINE</s></p></chap></body></text></archimedes>
