=== SeanyWang/despecs/texts/archimedesOldCVSRepository/archimedes/dtd/chunks.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT archimedes (chunk)+>
<!ATTLIST archimedes
        xmlns:xml       CDATA           #FIXED "http://www.w3.org/XML/1998/namespace"

     >

<!ELEMENT chunk (description|name|nodeset)*>
<!ATTLIST chunk
  xmlns CDATA #FIXED ''>

<!ELEMENT description EMPTY>
<!ATTLIST description
  xmlns CDATA #FIXED ''>

<!ELEMENT name (#PCDATA)>
<!ATTLIST name
  xmlns CDATA #FIXED ''>

<!ELEMENT nodeset (chunk|link)*>
<!ATTLIST nodeset
  xmlns CDATA #FIXED ''>

<!ELEMENT link EMPTY>

<!ATTLIST link
  xmlns CDATA #FIXED ''
  xmlns:xlink CDATA #FIXED 'http://www.w3.org/1999/xlink'
  xlink:href CDATA #REQUIRED>

=== SeanyWang/despecs/texts/archimedesOldCVSRepository/archimedes/chunking/specific_chuncks/monantheuil-spec-chunks.xml
<?xml version="1.0"?>
<!DOCTYPE archimedes SYSTEM "../../dtd/chunks.dtd" >
<archimedes>

<chunk>
<name>Greek text</name>
<description></description>
<nodeset>
<link xlink:href="035.xml#id.000241"/>
<link xlink:href="035.xml#id.000244"/>
<link xlink:href="035.xml#id.000312"/>
<link xlink:href="035.xml#g0110103"/>
<link xlink:href="035.xml#g0110201"/>
<link xlink:href="035.xml#id.000340"/>
<link xlink:href="035.xml#g0110203"/>
<link xlink:href="035.xml#id.000341"/>
<link xlink:href="035.xml#id.000398"/>
<link xlink:href="035.xml#id.000413"/>
<link xlink:href="035.xml#g0120102"/>
<link xlink:href="035.xml#id.000425"/>
<link xlink:href="035.xml#g0120104"/>
<link xlink:href="035.xml#id.000436"/>
<link xlink:href="035.xml#g0120202"/>
<link xlink:href="035.xml#g0120203"/>
<link xlink:href="035.xml#g0120203a"/>
<link xlink:href="035.xml#id.000458"/>
<link xlink:href="035.xml#g0120204"/>
<link xlink:href="035.xml#g0120205"/>
<link xlink:href="035.xml#g0120205a"/>
<link xlink:href="035.xml#g0120205b"/>
<link xlink:href="035.xml#id.000488"/>
<link xlink:href="035.xml#g0120302a"/>
<link xlink:href="035.xml#g0120303"/>
<link xlink:href="035.xml#g0120401"/>
<link xlink:href="035.xml#g0120401a"/>
<link xlink:href="035.xml#id.000513"/>
<link xlink:href="035.xml#id.000532"/>
<link xlink:href="035.xml#g0120502"/>
<link xlink:href="035.xml#g0120503"/>
<link xlink:href="035.xml#g0120601"/>
<link xlink:href="035.xml#g0120602"/>
<link xlink:href="035.xml#id.000553"/>
<link xlink:href="035.xml#g0120702"/>
<link xlink:href="035.xml#g0120704"/>
<link xlink:href="035.xml#g0120705"/>
<link xlink:href="035.xml#id.000585"/>
<link xlink:href="035.xml#g0120707"/>
<link xlink:href="035.xml#g0120708"/>
<link xlink:href="035.xml#g0120708a"/>
<link xlink:href="035.xml#g0120801"/>
<link xlink:href="035.xml#g0120802"/>
<link xlink:href="035.xml#id.000619"/>
<link xlink:href="035.xml#g0120804"/>
<link xlink:href="035.xml#g0120805"/>
<link xlink:href="035.xml#g0120806"/>
<link xlink:href="035.xml#g0120807"/>
<link xlink:href="035.xml#g0120808"/>
<link xlink:href="035.xml#g0120809"/>
<link xlink:href="035.xml#id.000657"/>
<link xlink:href="035.xml#g0121001"/>
<link xlink:href="035.xml#g0121002"/>
<link xlink:href="035.xml#g0121003"/>
<link xlink:href="035.xml#id.000672"/>
<link xlink:href="035.xml#g0121102"/>
<link xlink:href="035.xml#g0121201"/>
<link xlink:href="035.xml#id.000689"/>
<link xlink:href="035.xml#id.000703"/>
<link xlink:href="035.xml#g0121302"/>
<link xlink:href="035.xml#g0121302a"/>
<link xlink:href="035.xml#g0121303"/>
<link xlink:href="035.xml#g0121304"/>
<link xlink:href="035.xml#g0121401"/>
<link xlink:href="035.xml#g0121402"/>
<link xlink:href="035.xml#g0121402a"/>
<link xlink:href="035.xml#g0121402b"/>
<link xlink:href="035.xml#g0121404"/>
<link xlink:href="035.xml#g0121501"/>
<link xlink:href="035.xml#id.000775"/>
<link xlink:href="035.xml#g0121503"/>
<link xlink:href="035.xml#g0121504"/>
<link xlink:href="035.xml#g0121506"/>
<link xlink:href="035.xml#g0121506a"/>
<link xlink:href="035.xml#g0121506b"/>
<link xlink:href="035.xml#g0121508"/>
<link xlink:href="035.xml#g0121508a"/>
<link xlink:href="035.xml#g0121509"/>
<link xlink:href="035.xml#g0121510"/>
<link xlink:href="035.xml#id.000796"/>
<link xlink:href="035.xml#g0130102"/>
<link xlink:href="035.xml#g0130102a"/>
<link xlink:href="035.xml#g0130102b"/>
<link xlink:href="035.xml#g0130103"/>
<link xlink:href="035.xml#g0130105"/>
<link xlink:href="035.xml#id.000813"/>
<link xlink:href="035.xml#g0130107"/>
<link xlink:href="035.xml#g0130108"/>
<link xlink:href="035.xml#g0130108a"/>
<link xlink:href="035.xml#g0130108b"/>
<link xlink:href="035.xml#id.000847"/>
<link xlink:href="035.xml#g0130202"/>
<link xlink:href="035.xml#g0130203"/>
<link xlink:href="035.xml#g0130203a"/>
<link xlink:href="035.xml#g0130204"/>
<link xlink:href="035.xml#g0130204a"/>
<link xlink:href="035.xml#g0130204b"/>
<link xlink:href="035.xml#g0130205"/>
<link xlink:href="035.xml#g0130205a"/>
<link xlink:href="035.xml#g0130206"/>
<link xlink:href="035.xml#g0130207"/>
<link xlink:href="035.xml#g0130208"/>
<link xlink:href="035.xml#g0130209"/>
<link xlink:href="035.xml#g0130209a"/>
<link xlink:href="035.xml#g0130210"/>
<link xlink:href="035.xml#id.000899"/>
<link xlink:href="035.xml#id.000901"/>
<link xlink:href="035.xml#g0130301"/>
<link xlink:href="035.xml#g0130302"/>
<link xlink:href="035.xml#g0130302a"/>
<link xlink:href="035.xml#g0130302b"/>
<link xlink:href="035.xml#g0130302c"/>
<link xlink:href="035.xml#g0130302d"/>
<link xlink:href="035.xml#id.000950"/>
<link xlink:href="035.xml#g0130304"/>
<link xlink:href="035.xml#g0130305"/>
<link xlink:href="035.xml#g0130306"/>
<link xlink:href="035.xml#g0130307"/>
<link xlink:href="035.xml#g0130308"/>
<link xlink:href="035.xml#id.000993"/>
<link xlink:href="035.xml#g0130401a"/>
<link xlink:href="035.xml#g0130402"/>
<link xlink:href="035.xml#g0130402a"/>
<link xlink:href="035.xml#g0130402b"/>
<link xlink:href="035.xml#g0130402c"/>
<link xlink:href="035.xml#g0130403"/>
<link xlink:href="035.xml#g0130404"/>
<link xlink:href="035.xml#g0130404a"/>
<link xlink:href="035.xml#g0130405"/>
<link xlink:href="035.xml#g0130405a"/>
<link xlink:href="035.xml#g0130405b"/>
<link xlink:href="035.xml#g0130406"/>
<link xlink:href="035.xml#g0130408"/>
<link xlink:href="035.xml#g0130408a"/>
<link xlink:href="035.xml#g0130409"/>
<link xlink:href="035.xml#id.001137"/>
<link xlink:href="035.xml#id.001139"/>
<link xlink:href="035.xml#g0130503"/>
<link xlink:href="035.xml#g0130504"/>
<link xlink:href="035.xml#g0130505"/>
<link xlink:href="035.xml#g0130505a"/>
<link xlink:href="035.xml#id.001218"/>
<link xlink:href="035.xml#g0130507a"/>
<link xlink:href="035.xml#g0130508"/>
<link xlink:href="035.xml#g0130508a"/>
<link xlink:href="035.xml#id.001264"/>
<link xlink:href="035.xml#g0130510"/>
<link xlink:href="035.xml#g0130511"/>
<link xlink:href="035.xml#g0130511a"/>
<link xlink:href="035.xml#g0130512"/>
<link xlink:href="035.xml#g0130512a"/>
<link xlink:href="035.xml#g0130513"/>
<link xlink:href="035.xml#g0130514"/>
<link xlink:href="035.xml#g0130514a"/>
<link xlink:href="035.xml#id.001438"/>
<link xlink:href="035.xml#g0130515a"/>
<link xlink:href="035.xml#g0130515b"/>
<link xlink:href="035.xml#g0130516"/>
<link xlink:href="035.xml#g0130517"/>
<link xlink:href="035.xml#g0130517a"/>
<link xlink:href="035.xml#id.001454"/>
<link xlink:href="035.xml#id.001456"/>
<link xlink:href="035.xml#g0130602"/>
<link xlink:href="035.xml#g0130602a"/>
<link xlink:href="035.xml#g0130603"/>
<link xlink:href="035.xml#g0130603a"/>
<link xlink:href="035.xml#id.001498"/>
<link xlink:href="035.xml#id.001500"/>
<link xlink:href="035.xml#g0130702"/>
<link xlink:href="035.xml#g0130703"/>
<link xlink:href="035.xml#g0130704"/>
<link xlink:href="035.xml#id.001578"/>
<link xlink:href="035.xml#id.001580"/>
<link xlink:href="035.xml#g0130802"/>
<link xlink:href="035.xml#g0130803"/>
<link xlink:href="035.xml#g0130804"/>
<link xlink:href="035.xml#g0130805"/>
<link xlink:href="035.xml#id.001665"/>
<link xlink:href="035.xml#id.001665a"/>
<link xlink:href="035.xml#id.001665b"/>
<link xlink:href="035.xml#id.001665c"/>
<link xlink:href="035.xml#g0130808"/>
<link xlink:href="035.xml#g0130808a"/>
<link xlink:href="035.xml#g0130808b"/>
<link xlink:href="035.xml#g0130808c"/>
<link xlink:href="035.xml#g0130809"/>
<link xlink:href="035.xml#g0130809a"/>
<link xlink:href="035.xml#g0130812"/>
<link xlink:href="035.xml#g0130813"/>
<link xlink:href="035.xml#id.001683"/>
<link xlink:href="035.xml#id.001684"/>
<link xlink:href="035.xml#id.001743"/>
<link xlink:href="035.xml#id.001745"/>
<link xlink:href="035.xml#g0130902"/>
<link xlink:href="035.xml#g0130903"/>
<link xlink:href="035.xml#g0130904"/>
<link xlink:href="035.xml#g0130904a"/>
<link xlink:href="035.xml#id.001790"/>
<link xlink:href="035.xml#id.001792"/>
<link xlink:href="035.xml#g0131002"/>
<link xlink:href="035.xml#g0131002a"/>
<link xlink:href="035.xml#g0131003"/>
<link xlink:href="035.xml#g0131004"/>
<link xlink:href="035.xml#id.001811"/>
<link xlink:href="035.xml#id.001813"/>
<link xlink:href="035.xml#g0131101"/>
<link xlink:href="035.xml#g0131102"/>
<link xlink:href="035.xml#g0131102a"/>
<link xlink:href="035.xml#g0131103"/>
<link xlink:href="035.xml#id.001832"/>
<link xlink:href="035.xml#id.001834"/>
<link xlink:href="035.xml#g0131202"/>
<link xlink:href="035.xml#g0131203"/>
<link xlink:href="035.xml#g0131203a"/>
<link xlink:href="035.xml#g0131204"/>
<link xlink:href="035.xml#g0131205"/>
<link xlink:href="035.xml#g0131205a"/>
<link xlink:href="035.xml#id.001882"/>
<link xlink:href="035.xml#id.001884"/>
<link xlink:href="035.xml#g0131302"/>
<link xlink:href="035.xml#g0131302a"/>
<link xlink:href="035.xml#g0131303"/>
<link xlink:href="035.xml#g0131303a"/>
<link xlink:href="035.xml#g0131303b"/>
<link xlink:href="035.xml#id.001914"/>
<link xlink:href="035.xml#id.001916"/>
<link xlink:href="035.xml#g0131402"/>
<link xlink:href="035.xml#id.001940"/>
<link xlink:href="035.xml#id.001942"/>
<link xlink:href="035.xml#g0131502"/>
<link xlink:href="035.xml#g0131503"/>
<link xlink:href="035.xml#g0131504"/>
<link xlink:href="035.xml#g0131504a"/>
<link xlink:href="035.xml#g0131504b"/>
<link xlink:href="035.xml#g0131505"/>
<link xlink:href="035.xml#g0131505a"/>
<link xlink:href="035.xml#g0131506"/>
<link xlink:href="035.xml#g0131507"/>
<link xlink:href="035.xml#id.001964"/>
<link xlink:href="035.xml#id.001966"/>
<link xlink:href="035.xml#g0131603"/>
<link xlink:href="035.xml#g0131604"/>
<link xlink:href="035.xml#g0131604a"/>
<link xlink:href="035.xml#g0131605"/>
<link xlink:href="035.xml#g0131606"/>
<link xlink:href="035.xml#id.001992"/>
<link xlink:href="035.xml#id.001994"/>
<link xlink:href="035.xml#g0131702"/>
<link xlink:href="035.xml#g0131702a"/>
<link xlink:href="035.xml#g0131703"/>
<link xlink:href="035.xml#g0131703a"/>
<link xlink:href="035.xml#g0131704"/>
<link xlink:href="035.xml#g0131705"/>
<link xlink:href="035.xml#g0131705a"/>
<link xlink:href="035.xml#g0131705b"/>
